print ("Please enter an amount in cents less than a dollar.")
x = float(input())
print ("Your change will be:")
Q = int(x/25)
print("Q:",Q)
D = int((x - 25*Q) / 10)
print("D:",D)
N = int((x - 25*Q - 10*D)/5)
print("N:",N)
P= int((x - 25*Q - 10*D - 5*N))
print("P:",P)